adminUser: admin
adminPassword: changeme  # Should be changed and managed through secrets

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

securityContext:
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472

rbac:
  create: true
  pspEnabled: false

serviceAccount:
  create: true
  autoMount: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kubernetes-cluster:
      gnetId: 315
      revision: 3
      datasource: Prometheus
    istio-mesh:
      gnetId: 7639
      revision: 1
      datasource: Prometheus
    istio-service:
      gnetId: 7636
      revision: 1
      datasource: Prometheus

smtp:
  enabled: false  # Enable and configure if email notifications are needed
  host: smtp.gmail.com:587
  user: user
  password: password
  fromAddress: grafana@yourdomain.com
  fromName: Grafana Alert

alerting:
  enabled: true

security:
  oauth:
    enabled: false  # Enable and configure if OAuth is needed
  allowEmbedding: false
  cookieSecure: true
  sessionCookieSecure: true
  contentSecurityPolicy: true
  strictTransportSecurity: true
  xssProtection: true
  xContentTypeOptions: true
  referrerPolicy: "strict-origin-when-cross-origin" 