name: Test Infrastructure

on:
  workflow_dispatch:

env:
  TERRAFORM_VERSION: "1.0.0"

jobs:
  terraform-test:
    name: Infrastructure Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format
        run: |
          cd infrastructure
          terraform fmt -check -recursive || echo "Format check failed"
          terraform fmt -recursive
          terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          cd infrastructure
          terraform init -backend=false

      - name: Terraform Validate
        run: |
          cd infrastructure
          terraform validate 